### ISSUE TITLE
KSampler cannot work 

### ISSUE THREAD

**Issue by cardenluo** [RomanKuschanow/ComfyUI-Advanced-Latent-Control#1]
![image](https://github.com/RomanKuschanow/ComfyUI-Advanced-Latent-Control/assets/133877069/71643cbc-5bc9-418f-b71f-a750e0ef40c8)
No any change  for adjusting KSampler, but other two nodes is ok.

**Comment by RomanKuschanow** [comment]
In order for this to work with the multiplier parameter, it must be set to a value other than 1

**Comment by cardenluo** [comment]
it work now , that is funny , thanks
