### ISSUE TITLE
These seem great but not in ComfyUI manager? Are these still maintained?

### ISSUE THREAD

**Issue by Duemellon** [RomanKuschanow/ComfyUI-Advanced-Latent-Control#5]
I've had some recent non-manager nodes load & hosed my ComfyUI so I'm just checking to see if these are up to date? 

I am quite tired of the same compositions & this seem like they'll do the trick!

**Comment by RomanKuschanow** [comment]
Hello. Thank you for being so interested in this project. 

If I understand correctly, you cannot find these nodes in the manager. It has been added to the official list of custom nodes and has ID 693. 

Please describe the problem in more detail.

**Comment by Duemellon** [comment]
ah, I searched under Roman -- and didn't find it. 
Did a search for latent -- and didn't see it.
Now I found it. Installing now.
